### Criação do Partner 1
POST http://localhost:3000/partners/register
Content-Type: application/json

{
    "name": "Partner 1",
    "email": "partner1@user.com",
    "password": "secret",
    "company_name": "Company Name 1"
}

### Login Partner 1
# @name loginPartner1
POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "email": "partner1@user.com",
    "password": "secret"
}

###
@tokenPartner1 = {{ loginPartner1.response.body.token }}

### Criação do Partner 2
POST http://localhost:3000/partners/register
Content-Type: application/json

{
    "name": "Partner 2",
    "email": "partner2@user.com",
    "password": "secret",
    "company_name": "Company Name 2"
}

### Login Partner 2
# @name loginPartner2
POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "email": "partner1@user.com",
    "password": "secret"
}

###
@tokenPartner2 = {{ loginPartner2.response.body.token }}

### Criação do Customer 1
POST http://localhost:3000/customers/register 
Content-Type: application/json

{
    "name": "Customer 1",
    "email": "customer1@user.com",
    "password": "secret",
    "address": "adrress test",
    "phone": "33333333"
}

### Login do Customer 1
# @name loginCustomer1
POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "email": "customer1@user.com",
    "password": "secret"
}

###
@tokenCustomer1 = {{ loginCustomer1.response.body.token }}


### Criação do evento pelo parceiro
POST http://localhost:3000/partners/events 
Content-Type: application/json
Authorization: Bearer {{tokenPartner1}}

{
    "name": "Evento test 2",
    "description": "Descrição do evento 2",
    "date": "2025-01-01T00:00:00",
    "location": "Local evento Beach Party"
}

### Listagem dos eventos do parceiro
GET http://localhost:3000/partners/events
Authorization: Bearer {{tokenPartner1}}

### Listagem de um evento específico do parceiro
GET http://localhost:3000/partners/events/1
Authorization: Bearer {{tokenPartner1}}

### Listagem de eventos pelos clientes
GET http://localhost:3000/events

### Listagem de um evento especídigo pelos clientes
GET http://localhost:3000/events/1
