services:
  mysql:
    image: mysql:9.2.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tickets
    ports:
      - "33060:3306"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
